-- Migration: Create generated_music table
-- This stores all music generated by users instead of localStorage

CREATE TABLE IF NOT EXISTS generated_music (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  url TEXT NOT NULL,
  duration_seconds INTEGER DEFAULT 58,
  timestamp BIGINT NOT NULL,
  is_free_tier BOOLEAN DEFAULT true,
  cost_cents INTEGER DEFAULT 0,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster queries by user_id
CREATE INDEX IF NOT EXISTS idx_generated_music_user_id ON generated_music(user_id);

-- Create index for timestamp to get recent music first
CREATE INDEX IF NOT EXISTS idx_generated_music_timestamp ON generated_music(timestamp DESC);

-- Enable Row Level Security
ALTER TABLE generated_music ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own music
CREATE POLICY "Users can view their own music" ON generated_music
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can only insert their own music
CREATE POLICY "Users can insert their own music" ON generated_music
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can only update their own music
CREATE POLICY "Users can update their own music" ON generated_music
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Policy: Users can only delete their own music
CREATE POLICY "Users can delete their own music" ON generated_music
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_generated_music_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update updated_at
CREATE TRIGGER generated_music_updated_at
  BEFORE UPDATE ON generated_music
  FOR EACH ROW
  EXECUTE FUNCTION update_generated_music_updated_at();
